version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8989:80"
      #- "443:443"
    volumes:
      # app
      - ./app/src:/usr/share/nginx/html:rw
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./log/nginx/:/var/log/nginx/:rw
    networks:
      - net-php

  fpm:
    build: ./php-fpm
    expose:
      - "9000"
    volumes:
      - ./app/src:/usr/share/nginx/html:rw
      # Your php.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      #- ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      #- ./log/:/var/log/dnmp/:rw
    networks:
      - net-php
      - net-mysql
      - net-redis

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      # - ./conf/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
      #- ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      #- ./mysql/:/var/lib/mysql/:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "chac"

  redis:
    image: redis:4.0
    networks:
      - net-redis
    ports:
      - "6379:6379"
networks:
  net-php:
  net-mysql:
  net-redis: